# Generated by Django 4.2.6 on 2023-10-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobhandler', '0002_job_category_jobcategory_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to='static/media/companylogo')),
                ('website', models.URLField()),
            ],
        ),
    ]
