# Generated by Django 4.2.6 on 2023-10-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobhandler', '0003_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
