# Generated by Django 4.2.6 on 2023-10-11 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobhandler', '0005_job_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='locatoin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
