# Generated by Django 4.2.6 on 2023-10-11 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobhandler', '0006_job_locatoin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='locatoin',
            new_name='location',
        ),
    ]
