# Generated by Django 4.2.6 on 2023-10-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobhandler', '0008_alter_job_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
