# Generated by Django 4.2.6 on 2023-10-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobhandler', '0009_jobcategory_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcategory',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
