# Generated by Django 4.2.6 on 2023-10-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobhandler', '0010_alter_jobcategory_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='icon_code',
            field=models.CharField(default='flaticon-content', max_length=50),
        ),
    ]
